Repository clash-lang/clash-compiler, pull requests merged in 2020-04, with the labels that each got.

#1249 Allow QuickCheck 2.14
  clash-prelude/clash-prelude.cabal
Labels: backport 1.2

#1251 Add CoreTest to testsuite
  testsuite/Main.hs
  testsuite/clash-testsuite.cabal
  testsuite/src/Test/Tasty/Clash.hs
  testsuite/src/Test/Tasty/Clash/CoreTest.hs
Labels: needs-review

#1258 Infix use of `defaultSeqX` and `deepSeqX` righ-assoc
  changelog/2020-04-13T17:44:01+02:00_fix1256
  clash-prelude/src/Clash/XException.hs
Labels: backport 1.2

#1262 Update CI image
  .ci/docker/Dockerfile
  .ci/setup.sh
  .circleci/config.yml
  .gitlab-ci.yml
  clash-cores/clash-cores.cabal
Labels: backport

#1272 Update stack resolver to 15.9
  stack.yaml
Labels: backport 1.2

#1273 Bump time and extra to more recent versions
  clash-ghc/clash-ghc.cabal
  clash-lib/clash-lib.cabal
  clash-prelude/clash-prelude.cabal
Labels: backport 1.2

#863 Add scripts to build Debian packages
  bindist/linux/debian/Dockerfile
  bindist/linux/debian/README.md
  bindist/linux/debian/build_debs.py
  bindist/linux/debian/checksumdir.py
  bindist/linux/debian/mkBinDist.sh
Labels: WIP

#1279 Update install instructions for Windows
  docs/getting-started/installing.rst
Labels: backport 1.2

#1284 Don't expose Data.List.Extra
  clash-ghc/src-ghc/Clash/GHC/GenerateBindings.hs
  clash-lib/clash-lib.cabal
Labels: backport 1.2

#1285 FIx CHANGELOG.md formatting
  CHANGELOG.md
Labels: backport 1.2

#1294 Re-index in (Un)Signed fromSLV conversion
  changelog/2020-04-28T10_19_48+02_00_fix1292
  clash-lib/src/Clash/Backend/VHDL.hs
  tests/shouldwork/Basic/T1292.hs
  testsuite/Main.hs
Labels: backport 1.2

#1293 [snap] Install and expose cabal binary
  bindist/linux/snap/bindist.nix
  bindist/linux/snap/snap/snapcraft.yaml
Labels: backport 1.2

#1298 Fix clash-dev with ghc-8.10
  .ci/test.sh
  Clash.hs
  clash-dev
Labels: backport 1.2
