Repository clash-lang/clash-compiler, pull requests merged in 2020-07, with the labels that each got.

#1417 Retry snap/hackage publish on failure
  .ci/gitlab/publish.yml
Labels: backport 1.2

#1419 Basic Termination Analysis and Fuel
  clash-ghc/src-ghc/Clash/GHC/ClashFlags.hs
  clash-ghc/src-ghc/Clash/GHC/GenerateBindings.hs
  clash-lib/clash-lib.cabal
  clash-lib/src/Clash/Core/Evaluator/Models.hs
  clash-lib/src/Clash/Core/Evaluator/Semantics.hs
  clash-lib/src/Clash/Core/Termination.hs
  clash-lib/src/Clash/Driver/Types.hs
  clash-lib/src/Clash/Normalize.hs
  clash-lib/src/Clash/Normalize/DEC.hs
  clash-lib/src/Clash/Rewrite/Types.hs
  clash-lib/src/Clash/Rewrite/Util.hs
  clash-lib/tests/Test/Clash/Rewrite.hs
  docs/developing-hardware/flags.rst
  testsuite/src/Test/Tasty/Clash/CoreTest.hs
Labels: needs-review

#1425 Allow clash.cabal to access network
  bindist/linux/snap/snap/snapcraft.yaml
  changelog/2020-07-06T12_25_20+02_00_snap_network
Labels: backport 1.2

#1416 Run clashLibTests serially
  testsuite/src/Test/Tasty/Clash.hs
Labels: backport 1.2

#1427 Update release instructions
  bindist/README.md
Labels: backport 1.2

#1430 Upgrade to nixos 20.03
  changelog/2020-07-06T22_00_29+02_00_upgrade_nixpkgs
  nix/sources.json
  nix/sources.nix
Labels: backport 1.2

#1432 Fix generated `altpll` QSys file for Quartus CLI interface
  changelog/2020-07-08T10_23_27+02_00_fix_altpll_qsys
  clash-lib/src/Clash/Primitives/Intel/ClockGen.hs
Labels: backport 1.2

#1438 CircleCI: Set environment variables needed to run scripts
  .circleci/config.yml
Labels: backport 1.2

#1440 Prevent name clashes with VHDL imports
  changelog/2020-07-10T13_02_57+02_00_fix_imported_name_clashes
  clash-lib/src/Clash/Backend/VHDL.hs
  tests/shouldwork/Issues/T1439.hs
  testsuite/Main.hs
Labels: backport 1.2, needs-review

#1437 Add `PrintfArg` instance (going via `Integer`) for sized integral types
  clash-prelude/src/Clash/Sized/Internal/Index.hs
  clash-prelude/src/Clash/Sized/Internal/Signed.hs
  clash-prelude/src/Clash/Sized/Internal/Unsigned.hs
Labels: backport 1.2

#1443 Add vector monoid instance
  clash-prelude/src/Clash/Sized/Vector.hs
Labels: backport 1.2

#1447 Move tag check to ci/setup.hs
  .ci/setup.sh
  .ci/test.sh
Labels: backport 1.2

#1450 Fix starter project tests
  clash-starters/clash-example-project/src/Example/Project.hs
Labels: backport 1.2

#1462 Preprocess JSON files to be compatible with aeson-1.5
  changelog/2020-07-27T19_25_21+02_00_relax_aeson_dlist_versions
  clash-lib/clash-lib.cabal
  clash-lib/src/Data/Aeson/Extra.hs
  clash-lib/src/Data/List/Extra.hs
Labels: backport 1.2
