Repository clash-lang/clash-compiler, pull requests merged in 2020-03, with the labels that each got.

#1149 Single-dc, single field types cannot have a PortProduct annotation
  clash-lib/src/Clash/Netlist/Util.hs
  tests/shouldfail/TopEntity/T1063.hs
  testsuite/Main.hs
Labels: backport 1.2

#1170 Add auto backports using mergify
  .github/workflows/backport.yml
  .mergify.yml
Labels: backport 1.2

#1176 Use latest normalise plugin
  cabal.project
  clash-prelude/clash-prelude.cabal
  nix/sources.json
  stack.yaml
Labels: backport 1.2

#1179 Account for descending ranges in 'enumFromThen#'. Fix #1178
  clash-prelude/src/Clash/Sized/Internal/BitVector.hs
  clash-prelude/src/Clash/Sized/Internal/Index.hs
  clash-prelude/src/Clash/Sized/Internal/Signed.hs
  clash-prelude/src/Clash/Sized/Internal/Unsigned.hs
  clash-prelude/tests/Clash/Tests/BitVector.hs
  clash-prelude/tests/Clash/Tests/Signed.hs
  clash-prelude/tests/Clash/Tests/Unsigned.hs
Labels: backport 1.2

#1185 Use -fobject-code in repld clash-prelude target
  repld
Labels: backport 1.2

#1192 Workaround for https://github.com/commercialhaskell/stack/issues/5004
  docs/general/LICENSE
Labels: backport 1.2

#1186 Fix makeTopEntity for #1182 and add netlist tests
  clash-prelude/src/Clash/Annotations/TH.hs
  clash-prelude/tests/Clash/Tests/TopEntityGeneration.hs
  tests/shouldwork/TopEntity/PortGeneration.hs
  tests/shouldwork/TopEntity/T1182A.hs
  tests/shouldwork/TopEntity/T1182B.hs
  testsuite/Main.hs
Labels: backport 1.2

#1189 Run 'deadCode' after successful 'reduceConstant'. Fix #1187
  clash-lib/src/Clash/Normalize.hs
Labels: backport 1.2, needs-review

#1210 Remove <=8.2 CPP and compile with '-Wcompat'
  benchmark/clash-benchmark.cabal
  benchmark/profiling/prepare/clash-profiling-prepare.cabal
  benchmark/profiling/run/clash-profiling.cabal
  clash-cores/clash-cores.cabal
  clash-cosim/clash-cosim.cabal
  clash-dev
  clash-ghc/clash-ghc.cabal
  clash-ghc/src-bin-841/Clash/GHCi/UI.hs
  clash-ghc/src-bin-common/Clash/GHCi/Common.hs
  clash-lib/clash-lib.cabal
  clash-prelude/clash-prelude.cabal
  clash-prelude/src/Clash/Signal/BiSignal.hs
  clash-term/clash-term.cabal
  testsuite/clash-testsuite.cabal
Labels: backport 1.2, needs-review

#1213 Add blackboxes for Clash.Signal.Trace traceSignal functions (fixes #1198)
  clash-lib/prims/common/Clash_Signal_Trace.json
Labels: backport 1.2

#1219 Use qualified names for type defaults
  clash-ghc/src-bin-841/Clash/GHCi/UI.hs
  clash-ghc/src-bin-861/Clash/GHCi/UI.hs
  clash-ghc/src-bin-881/Clash/GHCi/UI.hs
Labels: backport 1.2

#1209 Verilog: allow non-contiguous field bit-patterns
  clash-lib/src/Clash/Backend/Verilog.hs
  clash-lib/src/Data/Semigroup/Monad/Extra.hs
  testsuite/Main.hs
  testsuite/src/Test/Tasty/Clash.hs
Labels: backport 1.2

#1225 Hackage releases based on ghc-8.6.5
  .gitlab-ci.yml
Labels: backport 1.2

#1228 Fix typo in Manifest
  clash-lib/src/Clash/Driver.hs
  clash-lib/src/Clash/Driver/Types.hs
Labels: backport 1.2

#1229 Only use cabal 2.4 for ghc 8.4.*
  .ci/setup.sh
Labels: backport 1.2

#1234 Add missing changelog entry
  changelog/2020-03-12T17:10:38+01:00_verilog_non_contiguous_fields
Labels: backport 1.2

#1233 Add `Vector.unfoldr`
  changelog/2020-03-19T11:30:00+01:00_unfoldr
  clash-prelude/src/Clash/Sized/Vector.hs
Labels: backport 1.2

#1235 Decouple evaluators
  Clash.hs
  benchmark/benchmark-normalization.hs
  benchmark/common/BenchmarkCommon.hs
  benchmark/profiling/run/profile-normalization-run.hs
  changelog/2020-03-19T14:57:31+01:00_Decouple_Evaluator
  clash-ghc/clash-ghc.cabal
  clash-ghc/src-bin-841/Clash/GHCi/UI.hs
  clash-ghc/src-bin-861/Clash/GHCi/UI.hs
  clash-ghc/src-bin-881/Clash/GHCi/UI.hs
  clash-ghc/src-ghc/Clash/GHC/Evaluator.hs
  clash-ghc/src-ghc/Clash/GHC/Evaluator.hs-boot
  clash-ghc/src-ghc/Clash/GHC/Evaluator/Primitive.hs
  clash-lib/clash-lib.cabal
  clash-lib/src/Clash/Core/Evaluator.hs
  clash-lib/src/Clash/Core/Evaluator/Types.hs
  clash-lib/src/Clash/Driver.hs
  clash-lib/src/Clash/Normalize.hs
  clash-lib/src/Clash/Normalize/DEC.hs
  clash-lib/src/Clash/Rewrite/Types.hs
  clash-lib/src/Clash/Rewrite/Util.hs
  testsuite/src/Test/Tasty/Clash/NetlistTest.hs
Labels: needs-review

#1243 `funSubst` works for all applications
  changelog/2020-03-24T13:08:40+01:00_fix1242
  clash-lib/src/Clash/Core/Type.hs
  tests/shouldwork/Basic/T1242.hs
  testsuite/Main.hs
Labels: backport 1.2

#1247 Don't `unsafeCoerce` from `Any @Nat` in `toBNat`
  changelog/2020-03-31T13:49:40+02:00_no_any_tobnat
  clash-prelude/src/Clash/Promoted/Nat.hs
Labels: backport 1.2
