Repository clash-lang/clash-compiler, pull requests merged in 2021-04, with the labels that each got.

#1735 Update tutorial
  clash-prelude/src/Clash/Tutorial.hs
  docs/getting-started/installing.rst
Labels: backport 1.4

#1739 Fix non-functional HiddenReset on delayI
  changelog/2021-04-01T11_12_04+02_00_no_reset_delayI
  clash-prelude/src/Clash/Signal/Delayed.hs
Labels: backport 1.4, bug

#1744 Fix rtd layout for install instructions
  docs/getting-started/installing.rst
Labels: backport 1.4

#1745 Normalize `Annotate` attributes
  changelog/2021-04-05T18_12_34+02_00_fix1742
  clash-ghc/src-ghc/Clash/GHC/GHC2Core.hs
  clash-ghc/src-ghc/Clash/GHC/GenerateBindings.hs
  tests/shouldwork/Issues/T1742.hs
  testsuite/Main.hs
Labels: backport 1.4

#1736 Update `TopEntity` annotation docs to include Enable parameter
  changelog/2021-03-28T16_34_02+02_00_fix646
  clash-prelude/src/Clash/Annotations/TopEntity.hs
Labels: backport 1.4

#1754 Improve and fix documentation
  clash-prelude/src/Clash/Annotations/Primitive.hs
  clash-prelude/src/Clash/Explicit/Signal/Delayed.hs
  clash-prelude/src/Clash/Signal/Delayed.hs
  clash-prelude/src/Clash/Signal/Delayed/Internal.hs
Labels: backport 1.4, documentation

#1759 Unroll `unconcat` in more situations than `m=0`
  changelog/2021-04-08T17_46_59+02_00_fix1756
  clash-lib/src/Clash/Normalize/PrimitiveReductions.hs
  clash-lib/src/Clash/Normalize/Transformations.hs
  tests/shouldwork/Issues/T1756.hs
  testsuite/Main.hs
Labels: backport 1.4

#1764 Only generate up to 3-tuple instances for Haddock
  .ci/nix_build.sh
  .gitlab-ci.yml
  clash-prelude/clash-prelude.cabal
  clash-prelude/src/Clash/CPP.hs
  clash-prelude/src/Clash/Class/AutoReg/Instances.hs
  clash-prelude/src/Clash/Class/BitPack.hs
  clash-prelude/src/Clash/Class/Counter/Internal.hs
  clash-prelude/src/Clash/Signal/Bundle.hs
  clash-prelude/src/Clash/XException.hs
Labels: backport 1.4

#1779 Account for undefined Vec spines in 'showX'
  changelog/2021-04-20T19_48_49+02_00_fix_1777
  clash-prelude/clash-prelude.cabal
  clash-prelude/src/Clash/Sized/Vector.hs
  clash-prelude/tests/Clash/Tests/Vector.hs
  clash-prelude/tests/unittests.hs
Labels: backport 1.4

#1783 Make `ShowX` instances produce valid Haskell
  changelog/2021-04-21T11_24_15+02_00_fix_1782
  clash-prelude/src/Clash/Explicit/BlockRam.hs
  clash-prelude/src/Clash/Prelude/BlockRam.hs
  clash-prelude/src/Clash/Sized/Vector.hs
  clash-prelude/src/Clash/XException.hs
  clash-prelude/src/Clash/XException/Internal.hs
  clash-prelude/tests/Clash/Tests/Vector.hs
Labels: needs-review

#1788 Fix #1786.
  changelog/2021-04-23T11_48_42+02_00_fix_1786
  clash-lib/src/Clash/Netlist/BlackBox/Util.hs
  tests/shouldwork/BlackBox/T1786.hs
  testsuite/Main.hs
Labels: backport 1.4, bug

#1790 Define a pull request template for GitHub
  .github/PULL_REQUEST_TEMPLATE.md
Labels: discussion
