Repository clash-lang/clash-compiler, pull requests merged in 2022-07, with the labels that each got.

#2257 Add vivado support to `clash-testsuite`
  .ci/bindist/linux/debian/focal/buildinfo.json
  .ci/docker/Dockerfile
  .ci/gitlab/benchmark.yml
  .ci/gitlab/common.yml
  .ci/gitlab/publish.yml
  .ci/gitlab/test.yml
  .ci/stack-8.6.5.yaml
  .github/workflows/ci.yml
  clash-cores/clash-cores.cabal
  tests/Main.hs
  tests/clash-testsuite.cabal
  tests/data-files/tcl/clash_namespace.tcl
  tests/src/Test/Tasty/Clash.hs
  tests/src/Test/Tasty/Ghdl.hs
  tests/src/Test/Tasty/Iverilog.hs
  tests/src/Test/Tasty/Modelsim.hs
  tests/src/Test/Tasty/Program.hs
  tests/src/Test/Tasty/SymbiYosys.hs
  tests/src/Test/Tasty/Verilator.hs
  tests/src/Test/Tasty/Vivado.hs
  tests/src/Test/Tasty/Vivado/GenTcl.hs
Labels: needs-review

#2273 Handle impredicative instantiation of error values
  changelog/2022-07-06T18_44_00+01_00_fix2272
  clash-dev.ps1
  clash-ghc/src-ghc/Clash/GHC/Evaluator.hs
  clash-lib/src/Clash/Core/Evaluator/Types.hs
  clash-term/clash-term.cabal
  tests/Main.hs
  tests/shouldwork/Issues/T2272.hs
Labels: backport 1.6

#2282 `clash-testsuite`: Fix, improve and harmonize simulator selection
  tests/Main.hs
  tests/src/Test/Tasty/Clash.hs
Labels: needs-review

#2286 Make sure fromSLV doesn't cause out of bound errors in VHDL simulation
  changelog/2022-07-19T19_23_48+02_00_fix_toEnum_OOB_errors
  clash-lib/src/Clash/Backend/VHDL.hs
  tests/Main.hs
  tests/shouldwork/Issues/T2220_toEnumOOB.hs
Labels: needs-review, backport 1.6
