Repository clash-lang/clash-compiler, pull requests merged in 2022-06, with the labels that each got.

#2195 Test suite: fix topEntity inclusion Ram/RMultiTop
  tests/shouldwork/Signal/Ram/RMulti.hs
  tests/shouldwork/Signal/Ram/RMultiTop.hs
Labels: needs-review, backport 1.6

#2241 Fix some blackbox issues
  changelog/2022-06-15T17_47_37+02_00_blackbox_parser_VAR
  changelog/2022-06-15T17_57_57+02_00_wrap_ARG_in_parens
  changelog/2022-06-15T18_16_00+02_00_fix_vhdl_shift_prims
  clash-lib/prims/commonverilog/Clash_Promoted_Nat.primitives.yaml
  clash-lib/prims/verilog/Clash_Intel_DDR.primitives.yaml
  clash-lib/prims/vhdl/Clash_Sized_Internal_BitVector.primitives.yaml
  clash-lib/prims/vhdl/Clash_Sized_Internal_Signed.primitives.yaml
  clash-lib/prims/vhdl/Clash_Sized_Internal_Unsigned.primitives.yaml
  clash-lib/prims/vhdl/GHC_Integer_Type.primitives.yaml
  clash-lib/prims/vhdl/GHC_Num_Integer.primitives.yaml
  clash-lib/prims/vhdl/GHC_Num_Natural.primitives.yaml
  clash-lib/prims/vhdl/GHC_Prim.primitives.yaml
  clash-lib/src/Clash/Netlist/BlackBox/Parser.hs
  clash-lib/src/Clash/Netlist/BlackBox/Util.hs
  clash-prelude/src/Clash/Tutorial.hs
  tests/shouldwork/Numbers/ShiftRotateBase.hs
Labels: backport 1.6

#2248 Substitute job name into CACHE_FALLBACK_KEY
  .ci/gitlab/common.yml
Labels: backport 1.6

#2247 Run `clash-testsuite` with 1 thread
  tests/clash-testsuite.cabal
Labels: backport 1.6

#2244 Speed up, harmonize BitReduction
  changelog/2022-06-17T10_37_07+02_00_bv_reduce
  clash-prelude/src/Clash/Sized/Internal/BitVector.hs
Labels: needs-review, backport 1.6

#2253 Use `ClashEnv` in Netlist Generation
  benchmark/profiling/run/profile-netlist-run.hs
  clash-lib/src/Clash/Backend/SystemVerilog.hs
  clash-lib/src/Clash/Backend/VHDL.hs
  clash-lib/src/Clash/Backend/Verilog.hs
  clash-lib/src/Clash/Netlist.hs
  clash-lib/src/Clash/Netlist/BlackBox.hs
  clash-lib/src/Clash/Netlist/Types.hs
  clash-lib/src/Clash/Netlist/Util.hs
  clash-lib/src/Clash/Primitives/Sized/ToInteger.hs
  clash-lib/src/Clash/Primitives/Sized/Vector.hs
  clash-lib/src/Clash/Primitives/Verification.hs
Labels: backport 1.6

#2230 Netlist track usage
  changelog/2022-06-21T09_53_32+02_00_netlist_usage.md
  clash-cores/src/Clash/Cores/LatticeSemi/ECP5/Blackboxes/IO.hs
  clash-cores/src/Clash/Cores/LatticeSemi/ICE40/Blackboxes/IO.hs
  clash-lib/prims/commonverilog/Clash_Explicit_SimIO.primitives.yaml
  clash-lib/prims/systemverilog/Clash_Explicit_DDR.primitives.yaml
  clash-lib/prims/systemverilog/Clash_Explicit_Testbench.primitives.yaml
  clash-lib/prims/systemverilog/Clash_Signal_Internal.primitives.yaml
  clash-lib/prims/systemverilog/Clash_Sized_Internal_BitVector.primitives.yaml
  clash-lib/prims/systemverilog/Clash_Sized_Vector.primitives.yaml
  clash-lib/prims/verilog/Clash_Explicit_BlockRam.primitives.yaml
  clash-lib/prims/verilog/Clash_Explicit_BlockRam_Blob.primitives.yaml
  clash-lib/prims/verilog/Clash_Explicit_BlockRam_File.primitives.yaml
  clash-lib/prims/verilog/Clash_Explicit_ROM.primitives.yaml
  clash-lib/prims/verilog/Clash_Explicit_ROM_Blob.primitives.yaml
  clash-lib/prims/verilog/Clash_Explicit_ROM_File.primitives.yaml
  clash-lib/prims/verilog/Clash_Signal_Internal.primitives.yaml
  clash-lib/prims/verilog/Clash_Sized_Internal_BitVector.primitives.yaml
  clash-lib/prims/verilog/Clash_Sized_Vector.primitives.yaml
  clash-lib/prims/vhdl/Clash_Explicit_BlockRam.primitives.yaml
  clash-lib/prims/vhdl/Clash_Explicit_BlockRam_Blob.primitives.yaml
  clash-lib/prims/vhdl/Clash_Explicit_BlockRam_File.primitives.yaml
  clash-lib/prims/vhdl/Clash_Explicit_ROM.primitives.yaml
  clash-lib/prims/vhdl/Clash_Explicit_ROM_Blob.primitives.yaml
  clash-lib/prims/vhdl/Clash_Explicit_ROM_File.primitives.yaml
  clash-lib/prims/vhdl/Clash_Explicit_Testbench.primitives.yaml
  clash-lib/prims/vhdl/Clash_Signal_Internal.primitives.yaml
  clash-lib/prims/vhdl/Clash_Sized_Internal_BitVector.primitives.yaml
  clash-lib/prims/vhdl/Clash_Sized_Vector.primitives.yaml
  clash-lib/src/Clash/Backend.hs
  clash-lib/src/Clash/Backend/SystemVerilog.hs
  clash-lib/src/Clash/Backend/VHDL.hs
  clash-lib/src/Clash/Backend/Verilog.hs
  clash-lib/src/Clash/Driver.hs
  clash-lib/src/Clash/Netlist.hs
  clash-lib/src/Clash/Netlist.hs-boot
  clash-lib/src/Clash/Netlist/BlackBox.hs
  clash-lib/src/Clash/Netlist/BlackBox/Parser.hs
  clash-lib/src/Clash/Netlist/BlackBox/Types.hs
  clash-lib/src/Clash/Netlist/BlackBox/Util.hs
  clash-lib/src/Clash/Netlist/Id.hs
  clash-lib/src/Clash/Netlist/Types.hs
  clash-lib/src/Clash/Netlist/Types.hs-boot
  clash-lib/src/Clash/Netlist/Util.hs
  clash-lib/src/Clash/Primitives/DSL.hs
  clash-lib/src/Clash/Primitives/Intel/ClockGen.hs
  clash-lib/src/Clash/Primitives/Sized/Vector.hs
  clash-lib/src/Clash/Primitives/Types.hs
  clash-lib/src/Clash/Primitives/Util.hs
  clash-lib/src/Clash/Primitives/Verification.hs
  tests/shouldwork/Naming/NameHint.hs
  tests/shouldwork/Naming/T1041.hs
  tests/shouldwork/Netlist/Identity.hs
  tests/shouldwork/Netlist/T1766.hs
  tests/shouldwork/TopEntity/T1182A.hs
  tests/shouldwork/TopEntity/T1182B.hs
Labels: needs-review
