Repository clash-lang/clash-compiler, pull requests merged in 2022-04, with the labels that each got.

#2153 Prim eval fixes
  changelog/2022-03-30T13_55_22+02_00_fix2154
  clash-ghc/src-ghc/Clash/GHC/Evaluator.hs
  clash-ghc/src-ghc/Clash/GHC/Evaluator/Primitive.hs
  clash-ghc/src-ghc/Clash/GHC/GHC2Core.hs
  clash-ghc/src-ghc/Clash/GHC/PartialEval/Eval.hs
  clash-lib/prims/common/Clash_Class_BitPack.primitives.yaml
  clash-lib/prims/common/Clash_GHC_GHC2Core.primitives.yaml
  clash-lib/prims/common/Clash_Normalize_Primitives.primitives.yaml
  clash-lib/prims/common/GHC_Err.primitives.yaml
  clash-lib/prims/common/GHC_TypeNats.primitives.yaml
  clash-lib/src/Clash/Core/PartialEval/NormalForm.hs
  clash-lib/src/Clash/Core/Util.hs
  clash-lib/src/Clash/Normalize/Primitives.hs
  clash-lib/src/Clash/Normalize/Transformations/Case.hs
  clash-lib/src/Clash/Normalize/Transformations/Inline.hs
  clash-prelude/src/Clash/Class/BitPack/Internal.hs
  tests/Main.hs
  tests/shouldwork/Basic/CaseOfErr.hs
  tests/shouldwork/Basic/SomeNatVal.hs
  tests/shouldwork/Basic/T1591.hs
  tests/shouldwork/Issues/T2154.hs
  tests/shouldwork/TopEntity/PortGeneration.hs
Labels: backport 1.6

#2157 Make sure the VHDL BB for Signed.fromInteger can handle any Netlist Expr
  changelog/2022-04-01T16_38_37+02_00_fix_Signed.fromInteger_VHDL_BB
  clash-lib/prims/vhdl/Clash_Sized_Internal_Signed.primitives.yaml
  clash-lib/src/Clash/Driver.hs
  clash-lib/src/Clash/Primitives/Sized/Signed.hs
  tests/Main.hs
  tests/shouldwork/Numbers/T2149.hs
Labels: backport 1.6

#2171 Fix `ANN TestBench` documentation
  changelog/2022-04-14T12_15_22+02_00_ann_testbench
  clash-prelude/src/Clash/Annotations/TopEntity.hs
Labels: needs-review, backport 1.4, backport 1.6

#2177 add scanrPar, scanlPar
  changelog/2022-04-21T12_34_12-05_00_add_scanpar
  changelog/2022-04-27T17_13_24+02_00_export_RTree_constrs
  clash-prelude/doc/scanlPar.graffle
  clash-prelude/doc/scanlPar.svg
  clash-prelude/src/Clash/Sized/RTree.hs
  clash-prelude/src/Clash/Sized/Vector.hs
Labels: needs-review
