Repository clash-lang/clash-compiler, pull requests merged in 2023-01, with the labels that each got.

#2382 Bump `doctest-parallel` (for Nix support)
  cabal.project
  clash-cores/clash-cores.cabal
  clash-cores/default.nix
  clash-lib/clash-lib.cabal
  clash-lib/default.nix
  clash-prelude/clash-prelude.cabal
  clash-prelude/default.nix
  nix/sources.json
  nix/sources.nix
Labels: backport 1.6

#2388 Various CI improvements
  .ci/all_check.py
  .github/workflows/ci.yml
Labels: backport 1.6

#2389 Correct FP Slack invite link
  README.md
Labels: backport 1.6

#2385 Note about fromInteger/toInteger in Concrete(ish) Fixed Types
  clash-prelude/src/Clash/Class/Resize.hs
  clash-prelude/src/Clash/Explicit/BlockRam.hs
  clash-prelude/src/Clash/Prelude/BlockRam.hs
  clash-prelude/src/Clash/Sized/Internal/BitVector.hs
  clash-prelude/src/Clash/Sized/Internal/Index.hs
  clash-prelude/src/Clash/Sized/Internal/Signed.hs
  clash-prelude/src/Clash/Sized/Internal/Unsigned.hs
  clash-prelude/src/Clash/Sized/RTree.hs
  clash-prelude/src/Clash/Sized/Vector.hs
Labels: backport 1.6

#2399 New: `clashCompileError`
  changelog/2023-01-06T16_16_24+01_00_add_clashCompileError
  clash-lib/clash-lib.cabal
  clash-lib/src/Clash/Driver.hs
  clash-lib/src/Clash/Primitives/Prelude.hs
  clash-prelude/src/Clash/Explicit/Prelude.hs
  clash-prelude/src/Clash/Prelude.hs
Labels: needs-review

#2402 Move small CI jobs back to shared runners
  .ci/gitlab/publish.yml
  .ci/gitlab/test.yml
  .gitlab-ci.yml
Labels: needs-review

#2392 Github CI: upgrade to actions/cache@v3 and fix caching on Windows
  .ci/build_clash_dev.sh
  .github/workflows/ci.yml
Labels: backport 1.6

#2403 CI: fix shared runners, use matrix
  .ci/gitlab/common.yml
  .ci/gitlab/publish.yml
  .ci/gitlab/test.yml
  .gitlab-ci.yml
  clash-lib/tests/Clash/Tests/Netlist/Id.hs
  clash-prelude/src/Clash/Annotations/Primitive.hs
  clash-prelude/src/Clash/Annotations/SynthesisAttributes.hs
  clash-prelude/src/Clash/Annotations/TopEntity.hs
  clash-prelude/src/Clash/Class/BitPack.hs
  clash-prelude/src/Clash/Class/Num.hs
  clash-prelude/src/Clash/Class/Resize.hs
  clash-prelude/src/Clash/Explicit/Mealy.hs
  clash-prelude/src/Clash/Explicit/Moore.hs
  clash-prelude/src/Clash/Explicit/Prelude/Safe.hs
  clash-prelude/src/Clash/Explicit/Synchronizer.hs
  clash-prelude/src/Clash/HaskellPrelude.hs
  clash-prelude/src/Clash/NamedTypes.hs
  clash-prelude/src/Clash/Prelude/BlockRam.hs
  clash-prelude/src/Clash/Prelude/BlockRam/Blob.hs
  clash-prelude/src/Clash/Prelude/DataFlow.hs
  clash-prelude/src/Clash/Prelude/Mealy.hs
  clash-prelude/src/Clash/Prelude/Moore.hs
  clash-prelude/src/Clash/Prelude/RAM.hs
  clash-prelude/src/Clash/Prelude/Safe.hs
  clash-prelude/src/Clash/Signal/Delayed.hs
Labels: backport 1.6

#2405 GitLab CI: Use manual cache bust token
  .ci/gitlab/common.yml
Labels: needs-review, backport 1.6

#2415 GitLab CI: Move snap publish to local
  .ci/gitlab/publish.yml
Labels: backport 1.6
