Repository clash-lang/clash-compiler, pull requests merged in 2024-01, with the labels that each got.

#2638 Clarify directory changelogs need to go into
  changelog/README.md
Labels: backport 1.8

#2622 Haddock: Fix very confusing formatting errors
  clash-cosim/src/Clash/CoSim/DSLParser.hs
  clash-ffi/src/Clash/FFI/VPI/Object/Value/Parse.hs
  clash-lib/src/Clash/Netlist/Util.hs
  clash-lib/src/Clash/Normalize/Transformations/Case.hs
  clash-lib/src/Clash/Normalize/Transformations/Cast.hs
  clash-lib/src/Clash/Normalize/Transformations/MultiPrim.hs
  clash-lib/src/Clash/Normalize/Transformations/Specialize.hs
  clash-lib/src/Clash/Primitives/DSL.hs
  clash-prelude/src/Clash/Annotations/Primitive.hs
  clash-prelude/src/Clash/Annotations/SynthesisAttributes.hs
  clash-prelude/src/Clash/Annotations/TopEntity.hs
  clash-prelude/src/Clash/Examples.hs
  clash-prelude/src/Clash/Explicit/BlockRam/File.hs
  clash-prelude/src/Clash/Explicit/ROM/File.hs
  clash-prelude/src/Clash/Explicit/Reset.hs
  clash-prelude/src/Clash/Explicit/Signal.hs
  clash-prelude/src/Clash/Explicit/Testbench.hs
  clash-prelude/src/Clash/Explicit/Verification.hs
  clash-prelude/src/Clash/Intel/ClockGen.hs
  clash-prelude/src/Clash/Prelude/BlockRam/File.hs
  clash-prelude/src/Clash/Prelude/DataFlow.hs
  clash-prelude/src/Clash/Prelude/ROM/File.hs
  clash-prelude/src/Clash/Promoted/Nat.hs
  clash-prelude/src/Clash/Signal.hs
  clash-prelude/src/Clash/Signal/BiSignal.hs
  clash-prelude/src/Clash/Signal/Bundle.hs
  clash-prelude/src/Clash/Sized/Fixed.hs
  clash-prelude/src/Clash/Sized/RTree.hs
  clash-prelude/src/Clash/Sized/Vector.hs
  clash-prelude/src/Clash/Tutorial.hs
  clash-prelude/src/Clash/Xilinx/ClockGen.hs
  tests/src/Test/Tasty/Ghdl.hs
  tests/src/Test/Tasty/Iverilog.hs
Labels: documentation, backport 1.6, backport 1.8

#2615 Amend `RELEASING.md`
  RELEASING.md
Labels: needs-review

#2637 clash-prelude: Add ShowX (Proxy a) instance
  changelog/2024-01-15T18_50_38-05_00_showx-proxy-instances
  clash-prelude/src/Clash/XException.hs
Labels: backport 1.8

#2633 clash-lib: Print constructor names in netlist errors
  clash-lib/src/Clash/Netlist.hs
Labels: backport 1.8

#2651 Fix Clash.Primitives.DSL.tuple on GHC-9.6
  clash-lib/src/Clash/Primitives/DSL.hs
  tests/Main.hs
Labels: backport 1.8
