Repository clash-lang/clash-compiler, pull requests merged in 2025-02, with the labels that each got.

#2879 Add hedgehog 1.5 support
  cabal.project
  clash-lib-hedgehog/clash-lib-hedgehog.cabal
  clash-prelude-hedgehog/clash-prelude-hedgehog.cabal
  clash-prelude/clash-prelude.cabal
Labels: needs-review

#2873 Avoid warnings instead of hiding them
  changelog/2024-11-16T11_59_31+01_00_avoid_using_unsafecoerce
  clash-prelude/src/Clash/Sized/Index.hs
  clash-prelude/src/Clash/Sized/Vector.hs
Labels: needs-review

#2881 Retry mmap failures in `clash-testsuite`
  .ci/stack-9.0.yaml
  .ci/stack-9.2.yaml
  .ci/stack-9.4.yaml
  .ci/stack-9.6.yaml
  .ci/stack-9.8.yaml
  cabal.project
  nix/overlay-ghc910.nix
  nix/overlay-ghc96.nix
  nix/overlay-ghc98.nix
  stack.yaml
  tests/Main.hs
  tests/clash-testsuite.cabal
Labels: backport 1.8

#2843 Elide unsafeCoerce from promoted nats
  clash-prelude/src/Clash/Promoted/Nat.hs
Labels: needs-review

#2890 Increase dependency bounds
  clash-ghc/clash-ghc.cabal
  clash-lib/clash-lib.cabal
  clash-prelude/clash-prelude.cabal
Labels: needs-review, backport 1.8

#2892 Remove CI job suite:cores
  .ci/gitlab/test.yml
Labels: needs-review
