Repository clash-lang/clash-compiler, pull requests merged in 2025-04, with the labels that each got.

#2919 Allow compilation on GHC 9.6.7
  .ci/docker/build-and-publish-docker-image.sh
  .ci/gitlab/benchmark.yml
  .ci/gitlab/common.yml
  .github/workflows/ci.yml
  .gitlab-ci.yml
  changelog/2025-04-02T09_08_44+02_00_add_ghc967_support
  clash-lib-hedgehog/src/Clash/Hedgehog/Unique.hs
  clash-lib/src/Clash/Core/FreeVars.hs
  clash-lib/src/Clash/Core/VarEnv.hs
  clash-lib/src/Clash/Data/UniqMap.hs
  clash-lib/src/Clash/Unique.hs
  clash-lib/src/Clash/Util/Graph.hs
Labels: needs-review, backport 1.8

#2933 Add Vivado SystemVerilog to CI
  .ci/gitlab/test.yml
  tests/Main.hs
  tests/src/Test/Tasty/Clash.hs
Labels: needs-review, backport 1.8

#2925 Strip ticks for literal parsing in `TermLiteral`
  changelog/2025-04-05T17_48_30+02_00_ignore_ticks
  clash-lib/src/Clash/Core/TermLiteral.hs
Labels: needs-review, backport 1.8

#2910 Clarify ShowX examples
  clash-prelude/src/Clash/XException.hs
  clash-prelude/src/Clash/XException/Internal.hs
Labels: backport 1.8

#2936 Rewrite `(+>>)` to no longer require `KnownNat`
  changelog/2025-04-18T15_27_46+02_00_less_knownnat
  clash-prelude/src/Clash/Sized/Vector.hs
Labels: needs-review

#2937 Update community links in root README
  README.md
Labels: needs-review, backport 1.8
